---
version: 0.0.1
name: hip-ops • Application Integration Operations Wiki
description: Your source for everything App Connect and IIBoC
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
exclude:
- ".gitignore"
- readme.md
