---
version: 0.0.1
name: hip-ops • Application Integration Operations Wiki
description: Your source for everything App Connect and IIBoC
collections:
  alerts:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: _alerts
    type: alerts
  values:
    layout: alerts
sass:
  sass_dir: _sass
  style: compressed
exclude:
- ".gitignore"
- readme.md
